### ISSUE TITLE
Uneven desynchronization every day

### ISSUE THREAD

**Issue by perikitodestino** [CmdrJane/time-and-wind#9] opened 2021-09-02 07:38 UTC
Hi!

I have set the configuration so that the day lasts longer than the night and since then the timetable is going wrong. Normally it would go to night at about 18:30 but now it does it differently. Sometimes when sleeping it is still night, sometimes the game considers that it is night when it is day... Not being constant I can't give precise information.

MC 1.17.1 with Fabric mod 1.4.2.

`{
  "minecraft:overworld": {
    "dayDuration": 18000,
    "nightDuration": 12000
  }
}`

Could it be a conflict of mine? Is there any way to provide more information?  Thanks!

**Comment by perikitodestino** [comment] 2021-09-02 08:30
PD: the mobs not despawn (or burn) in the day until a few minutes after sleeping

**Comment by CmdrJane** [comment] 2021-09-02 10:42
Can you add me in discord Iffy#6777?

**Comment by katubug** [comment] 2021-09-02 22:57
I am having this same issue, and it persists even with the mod removed. Can you tell me how this mod accomplishes what it does, so I can try to undo it without resetting the multiplayer world I'm on?

**Comment by CmdrJane** [comment] 2021-09-02 23:22
wait what
custom logic cant function without this mod, thats not possible

**Comment by CmdrJane** [comment] 2021-09-02 23:25
kk first of all i need  yours minecraft version and  list of ALL mods

**Comment by katubug** [comment] 2021-09-02 23:35
I'm thinking that the issue for me might be that I removed it from the
server but the clients still have it installed. Weirdly, my shaders show
the time of day that my minimap says, but when I turn them off, it'll be a
totally different light level.

It's temporarily fixed by /time set, but it desyncs again over time.

Here's the modpack: https://www.curseforge.com/minecraft/modpacks/cozy-chaos

1.3.0 is the version of the modpack  we're running. Minecraft 1.17.1,
Fabric 0.11.7 (I think, it's the most recent update).

**Comment by CmdrJane** [comment] 2021-09-02 23:39
uninstall from client, this mod is NOT supposed to be run client/server side only, its required on both sides

**Comment by CmdrJane** [comment] 2021-09-02 23:40
btw can at least one of you reach me in discord since i really want check wth i going on cause i cant reproduce this stuff on my end

**Comment by katubug** [comment] 2021-09-03 00:46
I don't have the energy to troubleshoot atm but I'll get back to you if it keeps happening. In the meantime, I think that my issue may have been a client/server issue. Somehow the modpack release only had the default 12000 day/12000 night setting, whereas the server had 20000/12000. Normally (in my experience) mods not installed on the server just won't be used if they're on the client only, so I thought it'd be an okay bandaid until I could push a fix. However, since it seems this mod does a lot of work on both client and server, it was probably a desync issue due to improperly matched configs.

I'll keep you posted!

**Comment by CmdrJane** [comment] 2021-09-03 00:57
i guess i need to add more checks on synchronizing stuff. anyway gotta sleep rn.

**Comment by CmdrJane** [comment] 2021-09-03 15:15
can you people please try this release [1.4.2-v2](https://github.com/CmdrJane/time-and-wind/releases/tag/taw-1.17.1-1.4.2-v2)

**Comment by perikitodestino** [comment] 2021-09-04 00:37
Not working, "Invalid player data" at connect to server... I remove old version and config in server/client sides but can't connect to server...

**Comment by CmdrJane** [comment] 2021-09-04 11:05
this mod doesnt touch player data at all, please provide list of all mods and your mc version and error logs

**Comment by CmdrJane** [comment] 2021-09-04 15:33
> 
> 
> Not working, "Invalid player data" at connect to server... I remove old version and config in server/client sides but can't connect to server...

also are you using any shader?

**Comment by CmdrJane** [comment] 2021-09-04 17:31
kk this stuff should be fixed in latest 1.17.1 release if not please report here

**Comment by perikitodestino** [comment] 2021-09-04 18:07
i have mc 1.17.1, don't worry, I remove the mod, not working correctly... ty

**Comment by CmdrJane** [comment] 2021-09-04 18:28
okay so it turn out that sync stuff is okay. I've already implemented fix for shaders, hopefully it will work

**Comment by CmdrJane** [comment] 2021-09-08 00:58
fixed in 4cf9e3ccf701169aa4a41fddca906b3637cd698a

**Closed by CmdrJane** 2021-09-08 00:58 UTC
